name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push User Service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service ./user-service
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service

    - name: Build and Push Item Service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/item-service ./item-service
        docker push ${{ secrets.DOCKER_USERNAME }}/item-service

    - name: Build and Push Report Service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/report-service ./report-service
        docker push ${{ secrets.DOCKER_USERNAME }}/report-service
